version: "3"
services:
  myportfolio:
    container_name: myportfolio
    build: .
    restart: always
    env_file:
      - .env
    depends_on:
      - mysql
    healthcheck:
      test: curl --fail -s http://localhost:5000/ || exit 1
      interval: 1m30s
      timeout: 10s
      retries: 3
  
  mysql:
    container_name: mysql
    image: mariadb
    restart: always
    env_file:
      - .env
    volumes:
      - mydatabase:/var/lib/mysql
    healthcheck:
      test: curl --fail -s http://localhost:3306/ || exit 1
      interval: 1m30s
      timeout: 10s
      retries: 3

  nginx:
    container_name: nginx
    image: jonasal/nginx-certbot
    restart: always
    environment:
      - CERTBOT_EMAIL=lmoraguez6380@floridapoly.edu
    ports:
      - 80:80
      - 443:443
    volumes:
      - nginx_secrets:/etc/letsencrypt
      - ./user_conf.d:/etc/nginx/user_conf.d
    depends_on:
      - myportfolio
    healthcheck:
      test: curl --fail -s https://luis-moraguez.duckdns.org/ || exit 1
      interval: 1m30s
      timeout: 10s
      retries: 3

volumes:
  mydatabase:
  nginx_secrets: