version: "3"
services:
  myportfolio:
    container_name: myportfolio
    build: .
    restart: always
    env_file:
      - .env
    depends_on:
      - mysql
    healthcheck:
      test: "curl -f localhost:5000"
      interval: 5s
      timeout: 5s
      retries: 20
  
  mysql:
    container_name: mysql
    image: mariadb
    restart: always
    env_file:
      - .env
    volumes:
      - mydatabase:/var/lib/mysql
    healthcheck:
      test: "/etc/init.d/mysql status"
      interval: 10s
      retries: 12

  nginx:
    container_name: nginx
    image: jonasal/nginx-certbot
    restart: always
    environment:
      - CERTBOT_EMAIL=lmoraguez6380@floridapoly.edu
    ports:
      - 80:80
      - 443:443
    volumes:
      - nginx_secrets:/etc/letsencrypt
      - ./user_conf.d:/etc/nginx/user_conf.d
    depends_on:
      - myportfolio
    healthcheck:
      test: "curl -f https://luis-moraguez.duckdns.org/"
      interval: 5s
      timeout: 5s
      retries: 20

volumes:
  mydatabase:
  nginx_secrets: