version: "3"
services:
  myportfolio:
    container_name: myportfolio
    build: .
    restart: always
    env_file:
      - .env
    depends_on:
      - mysql
    healthcheck:
      test: "wget --no-verbose --tries=1 --spider http://localhost || exit 1"
      interval: 2s
      timeout: 20s
      retries: 10
  
  mysql:
    container_name: mysql
    image: mariadb
    restart: always
    env_file:
      - .env
    volumes:
      - mydatabase:/var/lib/mysql
    healthcheck:
      test: "/usr/bin/mysql --user=root --password=$$MYSQL_ROOT_PASSWORD --execute \"SHOW DATABASES;\""
      interval: 2s
      timeout: 20s
      retries: 10

  nginx:
    container_name: nginx
    image: jonasal/nginx-certbot
    restart: always
    environment:
      - CERTBOT_EMAIL=lmoraguez6380@floridapoly.edu
    ports:
      - 80:80
      - 443:443
    volumes:
      - nginx_secrets:/etc/letsencrypt
      - ./user_conf.d:/etc/nginx/user_conf.d
    depends_on:
      - myportfolio
    healthcheck:
      test: "wget --no-verbose --tries=1 --spider http://localhost || exit 1"
      interval: 2s
      timeout: 20s
      retries: 10

volumes:
  mydatabase:
  nginx_secrets: